{% set name = "wlighter" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wlighter-{{ version }}.tar.gz
  sha256: 76003df4f73528b6a13c5cf1665706654d59ff3bf27691e2cef68f44c48c04fe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - requests

test:
  imports:
    - wlighter
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/DaniFdezAlvarez/wLighter
  summary: library to annotate RDF of ShEx containing wikidata URIs with a readable label
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marimeireles
